import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import SideBar from "@/components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white text-zinc-900 overflow-hidden">

        <div className="flex flex-col h-screen">

          {/* Navbar */}
          <header className="h-16 bg-white  px-4 flex items-center shrink-0">
            <NavBar />
          </header>

          {/* Content */}
          <div className="flex flex-1 overflow-hidden">

            {/* Sidebar */}
            <aside className="hidden lg:flex w-80 shrink-0">
              <SideBar />
            </aside>

            {/* Main */}
            <main className="flex-1 overflow-y-auto bg-zinc-100 p-6">
              {children}
            </main>

          </div>
        </div>

      </body>
    </html>
  );
}
